version: '3.8'

services:
 db:
     image: mysql:8
     container_name: pizzeria_db
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: pizzeria_project
       MYSQL_USER: user
       MYSQL_PASSWORD: 111111
     ports:
       - "3307:3306"

 app:
    build:
      context: ./
    container_name: pizzeria_app
    depends_on:
      - db
    environment:
      - JAVA_TOOL_OPTIONS="-Xmx512m"
#      - JAVA_TOOL_OPTIONS="-Xms256m -Xmx256m"
      - SPRING_DATASOURCE_URL=jdbc:mysql://pizzeria_db:3306/pizzeria_project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      - SPRING_FLYWAY_URL=jdbc:mysql://pizzeria_db:3306/pizzeria_project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      - SPRING_FLYWAY_USER=user
      - SPRING_FLYWAY_PASSWORD=111111
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=111111
    ports:
      - "80:8080"

